lsi:         false
name: Academie d'Espee
description: Kingdom of Atlantia
url: http://academie-de-espee.github.io
highlighter: pygments
markdown: kramdown
excerpt_separator: <!-- more -->
permalink:   pretty
exclude:
  - README.txt
  - Rakefile
defaults:
    - values:
        layout: default
