lsi:         false
name: Academie d'Espee
description: Kingdom of Atlantia
sass:
    style: :compressed
url: http://www.academiedespee.com/
highlighter: rouge
markdown: kramdown
excerpt_separator: <!-- more -->
permalink:   pretty
exclude:
  - README.txt
  - Rakefile
defaults:
    - values:
        layout: default
